const fs = require('fs');

const categories = [
  {
    id: 'navigation', label: '📂 Navigation', color: '#0969da', bg: 'rgba(9,105,218,0.1)', icon: '📂',
    commands: [
      { cmd: 'pwd', desc: 'Print working directory — shows your current location', example: 'pwd', syntax: 'pwd [OPTIONS]', flags: '✦ BASIC:\n-L  Follow symbolic links (default behavior)\n-P  Use physical path, resolving any symlinks', difficulty: 'beginner', examples: ['pwd', 'pwd -P'] },
      { cmd: 'ls', desc: 'The most common command to see files and folders inside your current location.', example: 'ls -lah', syntax: 'ls [OPTIONS] [PATH]', flags: '✦ BASIC VIEWS:\n-l  Detail view (shows size, owner, and date)\n-a  Show all files (includes hidden ones)\n-h  Easy-to-read sizes (KB, MB, GB)\n\n✦ SORTING:\n-t  Sort by newest files first\n-S  Sort by biggest files first\n-r  Reverse the sorting order\n\n✦ ADVANCED:\n-R  Recursive (look inside all sub-folders)\n-F  Add / after folders to identify them easily\n-i  Show unique ID (inode) for each file\n-1  List files in a single vertical column', difficulty: 'beginner', examples: ['ls -lah', 'ls -lt', 'ls -lS', 'ls -R', 'ls -1'] },
      { cmd: 'cd', desc: 'Change directory — navigate the filesystem tree', example: 'cd /var/www/html', syntax: 'cd [DIRECTORY]', flags: '✦ SHORTCUTS:\n~      Go to your home directory\n-      Go to your previous directory\n..     Go up one level (parent directory)\n../../ Go up two levels', difficulty: 'beginner', examples: ['cd /etc', 'cd ~', 'cd -', 'cd ../projects'] },
      { cmd: 'tree', desc: 'Display directory structure as a visual tree', example: 'tree -L 2 /var', syntax: 'tree [OPTIONS] [PATH]', flags: '✦ DISPLAY OPTIONS:\n-a  Show all files (including hidden ones)\n-d  List directories only (no files)\n-h  Print human-readable file sizes\n\n✦ FILTERING:\n-L n  Limit tree depth to n levels\n-I    Ignore files matching a pattern', difficulty: 'beginner', examples: ['tree', 'tree -L 2', 'tree -d -L 3 /etc'] },
      { cmd: 'pushd / popd', desc: 'Directory stack — push/pop directories for quick navigation', example: 'pushd /var/log', syntax: 'pushd [DIR] | popd', flags: '✦ COMMANDS:\npushd +n  Rotate stack n positions\npopd +n   Remove the nth entry from the stack\ndirs      List the current directory stack', difficulty: 'intermediate', examples: ['pushd /etc', 'popd', 'dirs -v'] },
      { cmd: 'realpath', desc: 'Resolve symlinks and print the absolute path', example: 'realpath ./mylink', syntax: 'realpath [OPTIONS] FILE', flags: '✦ BEHAVIOR:\n-m  Do not check if the path actually exists\n-s  Do not expand symbolic links\n\n✦ FORMATTING:\n--relative-to=DIR  Show path relative to a specific directory', difficulty: 'intermediate', examples: ['realpath myfile.txt', 'realpath --relative-to=/etc ./passwd'] },
    ]
  },
  {
    id: 'files', label: '📁 File Mgmt', color: '#1a7f37', bg: 'rgba(26,127,55,0.1)', icon: '📁',
    commands: [
      { cmd: 'mkdir', desc: 'Create new directories, including nested ones', example: 'mkdir -p projects/web/src', syntax: 'mkdir [OPTIONS] DIR', flags: '✦ CREATION:\n-p  Create parent directories as needed (no error if exists)\n-m  Set permissions (like chmod, e.g. 755)\n\n✦ OUTPUT:\n-v  Verbose (print message for each created directory)', difficulty: 'beginner', examples: ['mkdir mydir', 'mkdir -p a/b/c/d', 'mkdir -m 700 private'] },
      { cmd: 'touch', desc: 'Create empty files or update timestamps', example: 'touch index.html app.css', syntax: 'touch [OPTIONS] FILE', flags: '✦ TIMESTAMPS:\n-a  Change access time only\n-m  Change modification time only\n-t  Use a specific timestamp (YYYYMMDDhhmm)\n-c  Do not create any files', difficulty: 'beginner', examples: ['touch file.txt', 'touch -t 202401010000 file', 'touch file{1..5}.txt'] },
      { cmd: 'cp', desc: 'Copy files and directories preserving structure', example: 'cp -r src/ backup/', syntax: 'cp [OPTIONS] SRC DEST', flags: '✦ BASIC:\n-r  Recursive (required for copying directories)\n-i  Interactive (prompt before overwriting)\n\n✦ ADVANCED:\n-p  Preserve permissions, ownership, and timestamps\n-u  Update (copy only if source is newer than destination)\n-v  Verbose (show files being copied)', difficulty: 'beginner', examples: ['cp file.txt /tmp/', 'cp -rp /src /dest', 'cp -u *.log /backup/'] },
      { cmd: 'mv', desc: 'Move or rename files and directories', example: 'mv oldname.txt newname.txt', syntax: 'mv [OPTIONS] SRC DEST', flags: '✦ SAFETY:\n-i  Interactive (prompt before overwriting existing files)\n-n  No overwrite (never overwrite existing files)\n\n✦ BEHAVIOR:\n-u  Move only if source is newer than destination\n-v  Verbose (show files being moved)', difficulty: 'beginner', examples: ['mv file.txt /tmp/', 'mv -i old.txt new.txt', 'mv *.jpg images/'] },
      { cmd: 'rm', desc: 'Remove files and directories permanently', example: 'rm -rf /tmp/cache/', syntax: 'rm [OPTIONS] FILE', flags: '✦ DELETION:\n-r  Recursive (required for removing directories)\n-f  Force (ignore nonexistent files, never prompt)\n\n✦ SAFETY:\n-i  Interactive (prompt before every removal)\n-I  Prompt once before removing more than 3 files\n--preserve-root  Do not remove the root directory (default)', difficulty: 'beginner', examples: ['rm file.txt', 'rm -ri directory/', 'rm -f *.tmp'] },
      { cmd: 'ln', desc: 'Create hard or symbolic links between files', example: 'ln -s /etc/nginx nginx-conf', syntax: 'ln [OPTIONS] TARGET LINK', flags: '✦ LINK TYPE:\n-s  Create a symbolic link (symlink) instead of a hard link\n\n✦ BEHAVIOR:\n-f  Force (remove existing destination files)\n-r  Create a relative symlink relative to the link location\n-v  Verbose (show links being created)', difficulty: 'intermediate', examples: ['ln -s /var/www/html public', 'ln -sf new.conf current.conf'] },
      { cmd: 'rsync', desc: 'Efficient remote/local file syncing with delta transfers', example: 'rsync -avz src/ user@host:/dest/', syntax: 'rsync [OPTIONS] SRC DEST', flags: '✦ BEHAVIOR:\n-a  Archive mode (recursive, preserves permissions, times, etc.)\n-v  Verbose (show files being transferred)\n-z  Compress file data during the transfer\n\n✦ ADVANCED:\n--delete    Delete files in dest that are missing from source\n--exclude   Exclude files matching a pattern\n--progress  Show progress during transfer\n-n          Dry run (show what would be done without doing it)', difficulty: 'advanced', examples: ['rsync -av src/ dest/', 'rsync -avz --delete /local/ user@remote:/backup/', 'rsync -av --exclude=".git" . server:/app'] },
      { cmd: 'stat', desc: 'Display detailed file or filesystem status', example: 'stat /etc/passwd', syntax: 'stat [OPTIONS] FILE', flags: '✦ DISPLAY:\n-f  Display filesystem status instead of file status\n-c  Use custom specified format instead of default\n--printf  Like -c but interprets backslash escapes', difficulty: 'intermediate', examples: ['stat file.txt', 'stat -f /dev/sda', 'stat -c "%n %s %Y" file'] },
      { cmd: 'file', desc: 'Determine file type using magic number analysis', example: 'file unknown.bin', syntax: 'file [OPTIONS] FILE', flags: '✦ OUTPUT:\n-b  Brief mode (do not prepend filenames to output lines)\n-i  Output MIME type strings (e.g., text/plain)\n-z  Try to look inside compressed files', difficulty: 'beginner', examples: ['file image.png', 'file -i document', 'file *'] },
    ]
  },
  {
    id: 'viewing', label: '📖 Viewing', color: '#9a6700', bg: 'rgba(154,103,0,0.1)', icon: '📖',
    commands: [
      { cmd: 'cat', desc: 'Concatenate and display file contents', example: 'cat -n /etc/hosts', syntax: 'cat [OPTIONS] FILE', flags: '✦ FORMATTING:\n-n  Number all output lines\n-b  Number non-blank output lines\n-s  Squeeze multiple blank lines into one\n\n✦ SPECIAL CHARS:\n-A  Show all non-printing characters (tabs, newlines)', difficulty: 'beginner', examples: ['cat file.txt', 'cat -n app.log', 'cat file1 file2 > combined'] },
      { cmd: 'less', desc: 'Pager for viewing large files with search capability', example: 'less +F /var/log/syslog', syntax: 'less [OPTIONS] FILE', flags: '✦ DISPLAY OPTIONS:\n-N  Show line numbers\n-S  Chop long lines (do not wrap)\n-i  Ignore case in searches\n\n✦ STARTUP:\n+F  Start in follow mode (like tail -f)\n+/  Start at the first occurrence of a pattern', difficulty: 'beginner', examples: ['less large.log', 'less +F /var/log/auth.log', 'less -N file.txt'] },
      { cmd: 'head', desc: 'Output the first N lines of a file', example: 'head -n 50 server.log', syntax: 'head [OPTIONS] FILE', flags: '✦ LIMITS:\n-n N  Output the first N lines (default is 10)\n-c N  Output the first N bytes\n\n✦ FORMATTING:\n-q    Quiet (never print headers giving file names)', difficulty: 'beginner', examples: ['head file.txt', 'head -n 20 app.log', 'head -c 512 binary'] },
      { cmd: 'tail', desc: 'Output last N lines; follow live log updates', example: 'tail -f /var/log/nginx/access.log', syntax: 'tail [OPTIONS] FILE', flags: '✦ LIMITS:\n-n N  Output the last N lines (default is 10)\n-c N  Output the last N bytes\n\n✦ LIVE UPDATES:\n-f    Follow (output appended data as the file grows)\n-F    Follow and retry (keep trying to open if file is rotated)', difficulty: 'beginner', examples: ['tail -n 100 error.log', 'tail -f app.log', 'tail -F /var/log/syslog'] },
      { cmd: 'wc', desc: 'Count lines, words, characters, and bytes in files', example: 'wc -l access.log', syntax: 'wc [OPTIONS] FILE', flags: '✦ COUNTING OPTIONS:\n-l  Print the line count\n-w  Print the word count\n-c  Print the byte count\n-m  Print the character count\n-L  Print the length of the longest line', difficulty: 'beginner', examples: ['wc -l file.txt', 'wc -wlc report.txt', 'cat file | wc -l'] },
      { cmd: 'diff', desc: 'Compare files line by line showing differences', example: 'diff -u old.conf new.conf', syntax: 'diff [OPTIONS] FILE1 FILE2', flags: '✦ FORMAT OPTIONS:\n-u  Output in unified diff format (most common)\n-c  Output in context diff format\n--color  Colorize the output\n\n✦ BEHAVIOR:\n-i  Ignore case differences\n-r  Recursively compare any subdirectories found', difficulty: 'intermediate', examples: ['diff a.txt b.txt', 'diff -u old new', 'diff -r dir1/ dir2/'] },
      { cmd: 'od', desc: 'Dump file contents in octal, hex, or other formats', example: 'od -A x -t x1z file.bin', syntax: 'od [OPTIONS] FILE', flags: '✦ OUTPUT FORMAT (-t):\n-t x1  Hexadecimal bytes\n-t a   Named characters\n-c     C-style escaped characters\n\n✦ ADDRESS FORMAT (-A):\n-A x   Hexadecimal file offsets', difficulty: 'advanced', examples: ['od -x file.bin', 'od -c file', 'hexdump -C file.bin'] },
      { cmd: 'xxd', desc: 'Make hex dump of file or reverse a hex dump', example: 'xxd -l 256 /dev/urandom', syntax: 'xxd [OPTIONS] FILE', flags: '✦ DUMP OPTIONS:\n-l N  Stop after reading N octets (bytes)\n-s N  Start at absolute or relative offset N\n-c N  Format N octets per line\n\n✦ REVERSE:\n-r    Reverse operation: convert hex dump back to binary', difficulty: 'advanced', examples: ['xxd binary.dat', 'xxd -l 16 file', 'xxd -r hex.txt binary.bin'] },
    ]
  },
  {
    id: 'permissions', label: '🔐 Permissions', color: '#cf222e', bg: 'rgba(207,34,46,0.1)', icon: '🔐',
    commands: [
      { cmd: 'chmod', desc: 'Change file/directory permissions using octal or symbolic mode', example: 'chmod 755 deploy.sh', syntax: 'chmod [OPTIONS] MODE FILE', flags: '✦ COMMON MODES:\n755 = rwxr-xr-x (read/exec for all, write for owner)\n644 = rw-r--r-- (read for all, write for owner)\n600 = rw------- (read/write for owner only)\n+x  = Make file executable\n\n✦ OPTIONS:\n-R  Change files and directories recursively\n-v  Output a diagnostic for every file processed', difficulty: 'beginner', examples: ['chmod +x script.sh', 'chmod 644 config', 'chmod -R 755 /var/www'] },
      { cmd: 'chown', desc: 'Change file ownership (user and/or group)', example: 'chown -R www-data:www-data /var/www', syntax: 'chown [OPTIONS] USER[:GROUP] FILE', flags: '✦ OPTIONS:\n-R  Operate on files and directories recursively\n-v  Output a diagnostic for every file processed\n--from=USER  Change ownership only if current owner matches', difficulty: 'beginner', examples: ['chown user:group file', 'chown -R ubuntu /home/ubuntu', 'chown :developers shared/'] },
      { cmd: 'chgrp', desc: 'Change the group ownership of files', example: 'chgrp -R developers /srv/app', syntax: 'chgrp [OPTIONS] GROUP FILE', flags: '✦ OPTIONS:\n-R  Operate on files and directories recursively\n-v  Verbose mode\n-c  Like verbose but report only when a change is made', difficulty: 'intermediate', examples: ['chgrp staff file.txt', 'chgrp -R www-data /var/www'] },
      { cmd: 'umask', desc: 'Set default permissions mask for new files', example: 'umask 022', syntax: 'umask [MODE]', flags: '✦ MASKS:\n022  Dirs: 755 (rwxr-xr-x), Files: 644 (rw-r--r--)\n027  Dirs: 750 (rwxr-x---), Files: 640 (rw-r-----)\n077  Dirs: 700 (rwx------), Files: 600 (rw-------)\n\n✦ OPTIONS:\n-S  Print the current mask in symbolic format', difficulty: 'intermediate', examples: ['umask', 'umask 022', 'umask -S'] },
      { cmd: 'getfacl / setfacl', desc: 'Get/Set POSIX Access Control Lists for fine-grained permissions', example: 'setfacl -m u:john:rw file.txt', syntax: 'setfacl [OPTIONS] ACL FILE', flags: '✦ MODIFICATION:\n-m  Modify the current ACL of file(s)\n-x  Remove entries from the ACL\n-b  Remove all extended ACL entries\n\n✦ BEHAVIOR:\n-R  Apply operations to all files and directories recursively\n-d  Set the default ACL (directories only)', difficulty: 'advanced', examples: ['getfacl file.txt', 'setfacl -m u:bob:rwx file', 'setfacl -m g:devs:rx dir/'] },
      { cmd: 'sudo', desc: 'Execute commands as superuser or another user', example: 'sudo systemctl restart nginx', syntax: 'sudo [OPTIONS] COMMAND', flags: '✦ USAGE:\n-u  Run command as a specified user (default is root)\n-i  Simulate an initial root login shell\n-s  Run the shell specified by the SHELL environment variable\n\n✦ MANAGEMENT:\n-l  List user privileges or check a specific command\n-k  Invalidate the user\'s cached credentials', difficulty: 'beginner', examples: ['sudo apt update', 'sudo -u postgres psql', 'sudo -i'] },
      { cmd: 'passwd', desc: 'Change user password or account properties', example: 'passwd username', syntax: 'passwd [OPTIONS] [USER]', flags: '✦ MANAGEMENT:\n-l  Lock the password of the named account\n-u  Unlock the password of the named account\n-e  Expire the password (force user to change on next login)\n-d  Delete the password for the named account', difficulty: 'beginner', examples: ['passwd', 'sudo passwd john', 'sudo passwd -l baduser'] },
      { cmd: 'id', desc: 'Print real and effective user and group IDs', example: 'id -u ubuntu', syntax: 'id [OPTIONS] [USER]', flags: '✦ DISPLAY SPECIFICS:\n-u  Print only the effective user ID\n-g  Print only the effective group ID\n-G  Print all group IDs\n-n  Print names instead of numeric IDs (use with -u, -g, -G)', difficulty: 'beginner', examples: ['id', 'id -un', 'id -Gn user'] },
      { cmd: 'whoami', desc: 'Print effective user ID (current logged-in user)', example: 'whoami', syntax: 'whoami', flags: '✦ OPTIONS:\n--help     Display help information\n--version  Display version information', difficulty: 'beginner', examples: ['whoami'] },
    ]
  },
  {
    id: 'search', label: '🔍 Search', color: '#8250df', bg: 'rgba(130,80,223,0.1)', icon: '🔍',
    commands: [
      { cmd: 'find', desc: 'Recursively search for files by name, size, date, type, and more', example: 'find /var -name "*.log" -mtime +7 -delete', syntax: 'find [PATH] [CONDITIONS]', flags: '✦ CRITERIA:\n-name     Match file name (use quotes for wildcards)\n-type     f = file, d = directory, l = symlink\n-size +N  Larger than N (e.g., +100M)\n-mtime +N Modified more than N days ago\n-perm     Match exact permissions (e.g., 755)\n\n✦ ACTIONS:\n-exec CMD {} \\;  Execute command on matches\n-delete          Delete matched files', difficulty: 'intermediate', examples: ['find . -name "*.py"', 'find /tmp -size +100M -delete', 'find . -type f -newer ref.txt'] },
      { cmd: 'grep', desc: 'Search text using regex patterns in files or streams', example: 'grep -rn "TODO" --include="*.js" .', syntax: 'grep [OPTIONS] PATTERN [FILE]', flags: '✦ MATCHING OPTIONS:\n-i  Ignore case distinctions\n-E  Use extended regular expressions (like egrep)\n-v  Invert match (select non-matching lines)\n-r  Read all files under each directory recursively\n\n✦ OUTPUT OPTIONS:\n-n  Print line number with output lines\n-l  Print only the names of files containing matches\n-c  Print a count of matching lines for each file\n-A/B/C N  Print N lines of trailing/leading/context', difficulty: 'beginner', examples: ['grep "error" app.log', 'grep -rni "password" .', 'grep -E "^[0-9]+" data.txt'] },
      { cmd: 'awk', desc: 'Powerful text processing and data extraction language', example: "awk '{print $1, $3}' access.log", syntax: "awk 'PATTERN {ACTION}' FILE", flags: '✦ OPTIONS:\n-F  Define input field separator (e.g., -F: for /etc/passwd)\n-v  Assign a value to a variable (e.g., -v var=val)\n\n✦ BUILT-IN VARIABLES:\nNR  Current row/record number\nNF  Number of fields in current record\n$0  The entire line\n$1, $2, etc.  Specific fields by number', difficulty: 'advanced', examples: ["awk -F: '{print $1}' /etc/passwd", "awk 'NR>5' file.txt", "awk '{sum+=$2} END{print sum}' data"] },
      { cmd: 'sed', desc: 'Stream editor for filtering and transforming text', example: "sed -i 's/foo/bar/g' config.conf", syntax: 'sed [OPTIONS] SCRIPT [FILE]', flags: '✦ OPTIONS:\n-i  Edit files in-place (saves changes back to file)\n-n  Suppress automatic printing of pattern space\n-e  Add the script to the commands to be executed\n\n✦ COMMON COMMANDS:\ns/old/new/g  Substitute \'old\' with \'new\' globally\nd            Delete matching lines\np            Print matching lines', difficulty: 'advanced', examples: ["sed 's/old/new/g' file", "sed -n '5,10p' file", "sed '/^#/d' config.conf"] },
      { cmd: 'locate', desc: 'Quickly find files using an indexed database', example: 'locate -i nginx.conf', syntax: 'locate [OPTIONS] PATTERN', flags: '✦ SEARCH OPTIONS:\n-i  Ignore case distinctions\n-c  Output the number of matching entries instead of names\n-n N  Limit output to N results\n-e  Only print entries for files that currently exist\n--regex  Interpret PATTERN as a regular expression', difficulty: 'beginner', examples: ['locate nginx.conf', 'locate -i "*.jpg"', 'locate -c python'] },
      { cmd: 'which / whereis', desc: 'Locate executables and manual pages on PATH', example: 'which python3', syntax: 'which COMMAND | whereis COMMAND', flags: '✦ WHICH:\n-a  Print all matching executables in PATH\n\n✦ WHEREIS:\n-b  Search only for binaries\n-m  Search only for manual sections\n-s  Search only for sources', difficulty: 'beginner', examples: ['which node', 'which -a python', 'whereis nginx'] },
      { cmd: 'xargs', desc: 'Build and execute command lines from standard input', example: 'find . -name "*.log" | xargs rm', syntax: 'xargs [OPTIONS] [COMMAND]', flags: '✦ EXECUTION:\n-n N  Use at most N arguments per command line\n-P N  Run up to N processes in parallel\n-p    Prompt the user before executing each command\n\n✦ FORMATTING:\n-I{}  Replace occurrences of {} with the input\n-0    Input items are terminated by a null character (for find -print0)', difficulty: 'advanced', examples: ['ls | xargs echo', 'find . -name "*.tmp" | xargs -P4 rm', 'cat urls.txt | xargs -I{} curl {}'] },
      { cmd: 'cut', desc: 'Extract specific columns or characters from text', example: "cut -d: -f1,7 /etc/passwd", syntax: 'cut [OPTIONS] FILE', flags: '✦ SELECTION:\n-f  Select specific fields (e.g., -f1, -f1-3)\n-c  Select specific character positions (e.g., -c1-5)\n-b  Select specific bytes\n\n✦ DELIMITER:\n-d  Use a specific delimiter instead of TAB (e.g., -d,)', difficulty: 'intermediate', examples: ['cut -d, -f2 data.csv', 'cut -c1-10 file.txt', "echo 'a:b:c' | cut -d: -f2"] },
    ]
  },
  {
    id: 'system', label: '📊 System', color: '#bc4e00', bg: 'rgba(188,78,0,0.1)', icon: '📊',
    commands: [
      { cmd: 'top', desc: 'Interactive real-time process monitor', example: 'top -u www-data', syntax: 'top [OPTIONS]', flags: '✦ STARTUP:\n-u USER  Show only processes owned by USER\n-p PID   Monitor only specific PIDs\n-n N     Exit after updating N times\n-b       Batch mode (useful for redirecting to a file)\n\n✦ INTERACTIVE KEYS:\nk  Kill a process\nr  Renice (change priority) of a process\nq  Quit top', difficulty: 'beginner', examples: ['top', 'top -u nginx', 'top -n 1 -b | head -20'] },
      { cmd: 'htop', desc: 'Enhanced interactive process viewer with color UI', example: 'htop -u deploy', syntax: 'htop [OPTIONS]', flags: '✦ STARTUP:\n-u USER  Show only processes owned by USER\n-p PID   Show only specific comma-separated PIDs\n-d N     Delay between updates in tenths of a second\n-t       Show tree view by default', difficulty: 'beginner', examples: ['htop', 'htop -u postgres', 'htop -t'] },
      { cmd: 'df', desc: 'Report filesystem disk space usage', example: 'df -hT', syntax: 'df [OPTIONS] [FILE]', flags: '✦ DISPLAY:\n-h  Print sizes in human-readable powers of 1024 (e.g., 1023M)\n-T  Print filesystem type\n-i  List inode information instead of block usage\n-l  Limit listing to local file systems', difficulty: 'beginner', examples: ['df -h', 'df -hT', 'df -i /dev/sda1'] },
      { cmd: 'du', desc: 'Estimate file and directory disk usage', example: 'du -sh /* | sort -rh | head -10', syntax: 'du [OPTIONS] [FILE]', flags: '✦ DISPLAY OPTIONS:\n-s  Display only a total for each argument (summary)\n-h  Print sizes in human-readable format (e.g., 1K 234M 2G)\n-c  Produce a grand total\n-a  Write counts for all files, not just directories\n\n✦ FILTERING:\n--max-depth=N  Print total for a dir only if it is N or fewer levels deep', difficulty: 'beginner', examples: ['du -sh /var/log', 'du -sh * | sort -rh', 'du --max-depth=2 /home'] },
      { cmd: 'free', desc: 'Display amount of free and used memory in the system', example: 'free -h -s 2', syntax: 'free [OPTIONS]', flags: '✦ UNITS:\n-h  Show all output fields in human-readable format\n-m  Show output in megabytes\n-g  Show output in gigabytes\n\n✦ BEHAVIOR:\n-s N  Continuously display the result every N seconds\n-t    Show a line containing the totals', difficulty: 'beginner', examples: ['free -h', 'free -m', 'watch -n 2 free -h'] },
      { cmd: 'uptime', desc: 'Show how long system has been running and load average', example: 'uptime -p', syntax: 'uptime [OPTIONS]', flags: '✦ FORMATTING:\n-p  Show uptime in a pretty, human-readable format\n-s  System up since, in yyyy-mm-dd HH:MM:SS format\n-V  Display version information', difficulty: 'beginner', examples: ['uptime', 'uptime -p', 'uptime -s'] },
      { cmd: 'vmstat', desc: 'Report virtual memory, CPU, I/O statistics', example: 'vmstat 2 5', syntax: 'vmstat [OPTIONS] [DELAY [COUNT]]', flags: '✦ OUTPUT:\n-a  Print active/inactive memory instead of buffer/cache\n-d  Report disk statistics\n-s  Display a table of various event counters and memory stats\n-w  Wide output (makes it easier to read on large screens)', difficulty: 'intermediate', examples: ['vmstat', 'vmstat 1 10', 'vmstat -s'] },
      { cmd: 'iostat', desc: 'I/O statistics for devices and partitions', example: 'iostat -xz 1 5', syntax: 'iostat [OPTIONS] [INTERVAL [COUNT]]', flags: '✦ METRICS:\n-x  Display extended statistics (utilization, queue size, etc.)\n-c  Display the CPU utilization report\n-d  Display the device utilization report\n\n✦ FILTERING:\n-z  Omit output for any devices for which there was no activity\n-k / -m  Display statistics in kilobytes / megabytes per second', difficulty: 'advanced', examples: ['iostat -x 1', 'iostat -xz 2 5', 'iostat -d /dev/sda'] },
      { cmd: 'lsof', desc: 'List open files, sockets, and network connections', example: 'lsof -i :80', syntax: 'lsof [OPTIONS]', flags: '✦ FILTERING:\n-i      List IP sockets (e.g., -i :80 for port 80)\n-u USER List files opened by a specific user\n-p PID  List files opened by a specific process ID\n-c CMD  List files opened by processes starting with CMD\n+D DIR  Search recursively for open files within directory\n\n✦ OUTPUT:\n-t  Produce terse output containing only process IDs', difficulty: 'advanced', examples: ['lsof -i :443', 'lsof -u www-data', 'lsof +D /var/log'] },
      { cmd: 'uname', desc: 'Print system information (kernel, architecture, hostname)', example: 'uname -a', syntax: 'uname [OPTIONS]', flags: '✦ INFORMATION ELEMENTS:\n-a  Print all information\n-r  Print the kernel release\n-m  Print the machine hardware name (architecture)\n-n  Print the network node hostname\n-s  Print the kernel name\n-v  Print the kernel version', difficulty: 'beginner', examples: ['uname -a', 'uname -r', 'uname -m'] },
      { cmd: 'lscpu', desc: 'Display information about the CPU architecture', example: 'lscpu', syntax: 'lscpu [OPTIONS]', flags: '✦ FORMATTING:\n-e  Display CPU information in an extended, readable format\n-p  Print information in parsable format (CSV-like)\n-J  Format output as JSON', difficulty: 'beginner', examples: ['lscpu', 'lscpu -e'] },
      { cmd: 'lsblk', desc: 'List information about all available block devices (drives)', example: 'lsblk -f', syntax: 'lsblk [OPTIONS]', flags: '✦ OUTPUT COLUMNS:\n-f  Output info about filesystems (types, UUIDs, mountpoints)\n-m  Output info about device ownership and permissions\n-p  Print full device paths (e.g., /dev/sda)\n\n✦ SCOPE:\n-a  List all block devices (including empty ones)', difficulty: 'beginner', examples: ['lsblk', 'lsblk -f', 'lsblk -p'] },
      { cmd: 'journalctl', desc: 'Query and display logs from systemd journal', example: 'journalctl -u nginx.service -f', syntax: 'journalctl [OPTIONS]', flags: '✦ FILTERING:\n-u UNIT  Show logs for a specific systemd unit/service\n-k       Show kernel messages (like dmesg)\n-b       Show messages from the current boot\n\n✦ DISPLAY:\n-f    Follow the journal (like tail -f)\n-e    Jump to the end of the journal immediately\n-n N  Show the most recent N lines\n--no-pager  Print output directly without using a pager', difficulty: 'intermediate', examples: ['journalctl -xe', 'journalctl -u ssh -n 50', 'journalctl -b'] },
      { cmd: 'watch', desc: 'Execute a program periodically, showing output full screen', example: 'watch -n 1 "df -h"', syntax: 'watch [OPTIONS] COMMAND', flags: '✦ BEHAVIOR:\n-n SEC  Specify update interval in seconds (default is 2)\n-d      Highlight the differences between successive updates\n-t      Turn off the header showing interval, command, and time', difficulty: 'beginner', examples: ['watch ls -l', 'watch -n 0.5 nvidia-smi', 'watch -d free -m'] },
      { cmd: 'history', desc: 'Display the command history list with line numbers', example: 'history | grep docker', syntax: 'history [N]', flags: '✦ MANAGEMENT:\n-c  Clear the history list\n-d N  Delete the history entry at position N\n-w  Write current history to the history file immediately\n\n✦ USAGE:\n!N  Run command number N from the history', difficulty: 'beginner', examples: ['history', 'history 20', '!123'] },
      { cmd: 'man', desc: 'Display the on-line manual pages for commands', example: 'man tar', syntax: 'man [SECTION] COMMAND', flags: '✦ SEARCHING:\n-k  Search the short descriptions and manual page names for a keyword\n-f  Display only the short description (equivalent to whatis)\n\n✦ USAGE:\nman 5 config_file  Look up documentation in section 5 (formats)', difficulty: 'beginner', examples: ['man ls', 'man 5 crontab', 'man -k firewall'] },
    ]
  },
  {
    id: 'packages', label: '📦 Packages', color: '#0969da', bg: 'rgba(9,105,218,0.1)', icon: '📦',
    commands: [
      { cmd: 'apt', desc: 'Advanced Package Tool — primary package manager for Debian/Ubuntu', example: 'sudo apt install -y nginx', syntax: 'apt [COMMAND] [PACKAGE]', flags: '✦ REPOSITORY:\nupdate      Fetch the latest package lists from repositories\nupgrade     Upgrade all installed packages to latest versions\n\n✦ PACKAGE MGMT:\ninstall     Install one or more packages (-y skips confirmation)\nremove      Remove a package (keeps config files)\npurge       Remove a package AND its config files\nautoremove  Remove dependencies that are no longer needed\n\n✦ QUERYING:\nsearch      Search for a package by name/description\nshow        Show detailed information about a package', difficulty: 'beginner', examples: ['sudo apt update && sudo apt upgrade', 'sudo apt install git curl', 'apt search nodejs'] },
      { cmd: 'dpkg', desc: 'Low-level package manager for .deb files', example: 'dpkg -i package.deb', syntax: 'dpkg [OPTIONS] [PACKAGE]', flags: '✦ INSTALL/REMOVE:\n-i  Install a local .deb file\n-r  Remove an installed package\n-P  Purge a package and its configuration files\n\n✦ QUERYING:\n-l  List all installed packages\n-L  List all files installed by a specific package\n-s  Show status and details of an installed package\n--reconfigure  Reconfigure an already installed package', difficulty: 'intermediate', examples: ['dpkg -i myapp.deb', 'dpkg -l | grep nginx', 'dpkg -L openssh-server'] },
      { cmd: 'snap', desc: 'Snap package manager for universal Linux packages', example: 'snap install code --classic', syntax: 'snap [COMMAND] [PACKAGE]', flags: '✦ COMMON COMMANDS:\ninstall  Install a snap package (use --classic for unconfined access)\nremove   Remove an installed snap\nlist     List all installed snap packages\nfind     Search the snap store for packages\nrefresh  Update all or specific snap packages\ninfo     Show detailed information about a snap', difficulty: 'beginner', examples: ['snap install docker', 'snap list', 'snap refresh'] },
      { cmd: 'flatpak', desc: 'Flatpak package manager for sandboxed applications', example: 'flatpak install flathub org.gimp.GIMP', syntax: 'flatpak [COMMAND] [OPTIONS]', flags: '✦ COMMON COMMANDS:\ninstall    Install an application from a remote\nrun        Run an installed application\nlist       List all installed applications and runtimes\nuninstall  Remove an installed application\nupdate     Update all installed applications and runtimes', difficulty: 'intermediate', examples: ['flatpak install flathub com.spotify.Client', 'flatpak update', 'flatpak list'] },
    ]
  },
  {
    id: 'network', label: '🌐 Network', color: '#116329', bg: 'rgba(17,99,41,0.1)', icon: '🌐',
    commands: [
      { cmd: 'ping', desc: 'Send ICMP echo requests to test connectivity', example: 'ping -c 4 -i 0.5 google.com', syntax: 'ping [OPTIONS] HOST', flags: '✦ CONTROLS:\n-c N  Stop after sending N echo request packets\n-i N  Wait N seconds between sending each packet\n-s N  Specify the number of data bytes to be sent\n-t N  Set the IP Time to Live (TTL) value\n-q    Quiet output (show only summary lines at start/finish)', difficulty: 'beginner', examples: ['ping google.com', 'ping -c 5 8.8.8.8', 'ping -i 0.2 -c 100 server'] },
      { cmd: 'curl', desc: 'Transfer data to/from servers supporting many protocols', example: 'curl -s -o /dev/null -w "%{http_code}" https://api.github.com', syntax: 'curl [OPTIONS] URL', flags: '✦ REQUEST:\n-X  Specify HTTP method (GET, POST, PUT, DELETE)\n-H  Add an HTTP header (e.g., "Authorization: Bearer")\n-d  Send request body data (implies POST)\n\n✦ CONNECTION:\n-L  Follow HTTP redirects\n-k  Allow insecure SSL connections (skip cert validation)\n-u  Specify username and password (user:pass)\n\n✦ OUTPUT:\n-o  Write output to a specific file instead of stdout\n-s  Silent mode (do not show progress meter or error messages)', difficulty: 'intermediate', examples: ['curl https://api.github.com', 'curl -X POST -H "Content-Type: application/json" -d \'{"key":"val"}\' URL', 'curl -o file.tar.gz URL'] },
      { cmd: 'wget', desc: 'Non-interactive network downloader supporting HTTP, HTTPS, FTP', example: 'wget -c -q https://example.com/file.iso', syntax: 'wget [OPTIONS] URL', flags: '✦ DOWNLOAD:\n-c  Continue getting a partially-downloaded file\n-O  Save downloaded document as a specific filename\n-P  Save files to a specific directory prefix\n\n✦ BEHAVIOR:\n-q  Quiet mode (turn off output completely)\n-r  Turn on recursive retrieving (for downloading directories/sites)\n--limit-rate  Limit the download speed', difficulty: 'beginner', examples: ['wget https://example.com/file.zip', 'wget -c -O out.iso URL', 'wget -r -l2 https://docs.site.com'] },
      { cmd: 'ssh', desc: 'Secure Shell — encrypted remote login and command execution', example: 'ssh -i ~/.ssh/id_rsa user@192.168.1.10 -p 2222', syntax: 'ssh [OPTIONS] [USER@]HOST [CMD]', flags: '✦ CONNECTION:\n-i  Specify identity file (private key) for public key auth\n-p  Connect to a specific port on the remote host\n-v  Verbose mode (useful for debugging connection issues)\n\n✦ TUNNELING:\n-L  Local port forwarding (bind local port to remote address)\n-R  Remote port forwarding (bind remote port to local address)\n-N  Do not execute a remote command (useful for just forwarding ports)', difficulty: 'intermediate', examples: ['ssh user@server.com', 'ssh -i key.pem ubuntu@ec2-host', 'ssh -L 8080:localhost:80 user@remote'] },
      { cmd: 'scp', desc: 'Secure copy files between hosts over SSH', example: 'scp -r ./dist user@server:/var/www/', syntax: 'scp [OPTIONS] SRC DEST', flags: '✦ OPTIONS:\n-r  Recursively copy entire directories\n-P  Specify the port to connect to on the remote host\n-i  Specify identity file (private key)\n-C  Enable compression during transfer\n-q  Quiet mode (disables progress meter)', difficulty: 'intermediate', examples: ['scp file.txt user@host:/tmp/', 'scp -r ./project server:/srv/', 'scp user@host:/var/log/app.log .'] },
      { cmd: 'ip', desc: 'Show/manage network interfaces, routing, and tunnels', example: 'ip addr show eth0', syntax: 'ip [OPTIONS] OBJECT [COMMAND]', flags: '✦ ADDRESSES (ip addr):\nip a / addr show        List all IP addresses\nip addr add X/M dev IF  Add an IP address to an interface\n\n✦ ROUTES (ip route):\nip r / route show       Show the routing table\nip route add CIDR via GW Add a static route\n\n✦ LINKS (ip link):\nip link set IF up/down  Bring an interface up or down', difficulty: 'intermediate', examples: ['ip a', 'ip route show', 'ip addr add 10.0.0.1/24 dev eth0'] },
      { cmd: 'netstat / ss', desc: 'Display network connections, ports, and socket statistics', example: 'ss -tlnp', syntax: 'ss [OPTIONS] | netstat [OPTIONS]', flags: '✦ SOCKET TYPES:\n-t  Show only TCP sockets\n-u  Show only UDP sockets\n-l  Show only listening sockets\n\n✦ DETAILS:\n-n  Show numerical addresses instead of resolving hostnames\n-p  Show the process ID and name using the socket (requires sudo)\n-r  Show the routing table', difficulty: 'intermediate', examples: ['ss -tlnp', 'ss -anp | grep :80', 'netstat -tulnp'] },
      { cmd: 'traceroute', desc: 'Trace the network path packets take to a destination', example: 'traceroute -n google.com', syntax: 'traceroute [OPTIONS] HOST', flags: '✦ PROBING OPTIONS:\n-n  Do not resolve IP addresses to their domain names\n-m N  Set the maximum number of hops (max time-to-live)\n-w N  Set the time to wait for a response to a probe\n\n✦ PROTOCOLS:\n-I  Use ICMP ECHO for probes (instead of UDP)\n-T  Use TCP SYN for probes', difficulty: 'intermediate', examples: ['traceroute google.com', 'traceroute -n 8.8.8.8', 'traceroute -m 20 server.com'] },
      { cmd: 'nmap', desc: 'Network exploration and security scanning tool', example: 'nmap -sV -p 1-1000 192.168.1.0/24', syntax: 'nmap [OPTIONS] TARGET', flags: '✦ SCAN TYPES:\n-sV  Probe open ports to determine service/version info\n-O   Enable OS detection\n-sn  Ping scan only (disable port scan)\n-A   Enable OS detection, version detection, script scanning, etc.\n\n✦ TARGETING:\n-p   Specify ports to scan (e.g., -p 80,443 or -p 1-1024)\n-T4  Set execution timing template to fast', difficulty: 'advanced', examples: ['nmap 192.168.1.1', 'nmap -sV -p 80,443 host', 'nmap -sn 10.0.0.0/24'] },
      { cmd: 'tcpdump', desc: 'Capture and analyze network packets on an interface', example: 'tcpdump -i eth0 -n port 80', syntax: 'tcpdump [OPTIONS] [FILTER]', flags: '✦ CAPTURE:\n-i  Listen on a specific interface\n-c N  Exit after receiving N packets\n-n  Don\'t convert addresses to names (avoids DNS lookups)\n\n✦ FILE I/O:\n-w  Write raw packets to a pcap file\n-r  Read packets from a saved pcap file\n\n✦ OUTPUT:\n-X  Print data of each packet in hex and ASCII', difficulty: 'advanced', examples: ['tcpdump -i eth0', 'tcpdump -i any port 443 -w https.pcap', 'tcpdump -r capture.pcap'] },
      { cmd: 'dig', desc: 'DNS lookup utility for interrogating name servers', example: 'dig google.com MX', syntax: 'dig [OPTIONS] [ANY] [TYPE]', flags: '✦ QUERY FORMATTING:\n+short   Provide a terse, short answer only\n@SERVER  Send the query to a specific DNS server (e.g., @8.8.8.8)\n-x IP    Perform a reverse DNS lookup to resolve an IP to a domain name\n\n✦ COMMON TYPES:\nA, AAAA, MX, TXT, CNAME, NS, ANY', difficulty: 'intermediate', examples: ['dig example.com', 'dig +short A example.com', 'dig @8.8.8.8 google.com'] },
      { cmd: 'ufw', desc: 'Uncomplicated Firewall — user-friendly frontend for iptables', example: 'sudo ufw allow 80/tcp', syntax: 'ufw [COMMAND] [RULE]', flags: '✦ STATE MGMT:\nenable / disable  Turn the firewall on or off\nstatus numbered   Show active rules with ID numbers\nreload            Reload the firewall configuration\n\n✦ RULES:\nallow / deny      Allow or block traffic (e.g., allow ssh)\nlimit             Rate limit connections (helps block brute force)\ndelete N          Delete a specific rule by its number', difficulty: 'intermediate', examples: ['sudo ufw status', 'sudo ufw allow ssh', 'sudo ufw limit 22/tcp'] },
    ]
  },
  {
    id: 'process', label: '⚙️ Process', color: '#d4430d', bg: 'rgba(212,67,13,0.1)', icon: '⚙️',
    commands: [
      { cmd: 'ps', desc: 'Report a snapshot of current processes', example: 'ps aux --sort=-%mem | head -10', syntax: 'ps [OPTIONS]', flags: '✦ COMMONLY USED FORMATS:\naux  Show all processes for all users in a BSD-like format\n-ef  Show all processes in standard Unix format\n\n✦ FILTERING & SORTING:\n-u USER  Show processes for a specific user\n-p PID   Show information for specific PIDs\n--sort   Sort output by column (e.g., -%cpu or -%mem for descending)', difficulty: 'beginner', examples: ['ps aux', 'ps -ef | grep nginx', 'ps aux --sort=-%cpu | head'] },
      { cmd: 'kill', desc: 'Send signals to processes by PID', example: 'kill -9 1234', syntax: 'kill [SIGNAL] PID', flags: '✦ COMMON SIGNALS:\n-15 (SIGTERM)  Ask the process to terminate gracefully (default)\n-9  (SIGKILL)  Forcefully terminate the process immediately\n-1  (SIGHUP)   Hang up (often used to tell daemons to reload config)\n-19 (SIGSTOP)  Pause the process\n-18 (SIGCONT)  Resume a paused process', difficulty: 'beginner', examples: ['kill 1234', 'kill -9 5678', 'kill -HUP $(pgrep nginx)'] },
      { cmd: 'killall', desc: 'Kill all processes with a matching name', example: 'killall -9 firefox', syntax: 'killall [OPTIONS] NAME', flags: '✦ BEHAVIOR:\n-9  Send SIGKILL instead of SIGTERM\n-u  Kill only processes owned by a specific user\n-r  Interpret the process name pattern as a regular expression\n-w  Wait for all killed processes to die before returning\n-v  Verbose (report if signals were successfully sent)', difficulty: 'beginner', examples: ['killall nginx', 'killall -9 zombie-app', 'killall -u deploy'] },
      { cmd: 'jobs / bg / fg', desc: 'Manage background and foreground shell jobs', example: 'command & ; jobs ; fg %1', syntax: 'jobs | bg [%N] | fg [%N]', flags: '✦ COMMANDS:\njobs -l  List active jobs with their PIDs\nbg %N    Resume suspended job N in the background\nfg %N    Bring job N to the foreground\n&        (Suffix) run a command in the background immediately', difficulty: 'intermediate', examples: ['ping server &', 'jobs -l', 'fg %1'] },
      { cmd: 'nohup', desc: 'Run command immune to hangups (keeps running after logout)', example: 'nohup ./server.sh > server.log 2>&1 &', syntax: 'nohup COMMAND [ARGS] &', flags: '✦ USAGE NOTES:\n* Output is appended to `nohup.out` by default if not redirected.\n* Usually combined with `&` to place the process in the background.\n* Best practice: redirect both stdout and stderr (e.g., `> out.log 2>&1`)', difficulty: 'intermediate', examples: ['nohup python server.py &', 'nohup ./deploy.sh > deploy.log &'] },
      { cmd: 'nice / renice', desc: 'Run command with modified scheduling priority', example: 'nice -n 10 make -j4', syntax: 'nice -n N COMMAND | renice N -p PID', flags: '✦ PRIORITY LEVELS (Niceness):\n-20  Highest priority (requires root privileges)\n  0  Default scheduling priority\n 19  Lowest priority (nicest to other processes)\n\n✦ COMMANDS:\nnice -n N  Start a new command with niceness N\nrenice N   Alter the niceness of an already running process', difficulty: 'advanced', examples: ['nice -n 15 backup.sh', 'renice 5 -p 1234', 'nice -n -5 critical-app'] },
      { cmd: 'systemctl', desc: 'Control systemd services, sockets, and units', example: 'systemctl status nginx', syntax: 'systemctl [COMMAND] [UNIT]', flags: '✦ STATE COMMANDS:\nstart / stop / restart  Manage the running state of a service\nstatus                  View detailed status and recent logs\nreload                  Instruct a service to reload its configuration\n\n✦ BOOT COMMANDS:\nenable / disable        Set service to start (or not) at boot\nenable --now            Enable and start the service immediately\n\n✦ QUERYING:\nlist-units              List all loaded units in memory', difficulty: 'intermediate', examples: ['systemctl status nginx', 'systemctl restart mysql', 'systemctl enable --now docker'] },
      { cmd: 'cron / crontab', desc: 'Schedule periodic commands using cron syntax', example: 'crontab -e', syntax: 'crontab -e | crontab -l | crontab -r', flags: '✦ COMMANDS:\n-e  Edit your crontab file using the default editor\n-l  List the contents of your crontab\n-r  Remove your crontab entirely\n-u  Specify a user (requires root)\n\n✦ SYNTAX (MIN HR DOM MON DOW):\n* * * * *    Every minute\n0 2 * * *    Daily at 2:00 AM\n*/15 * * * * Every 15 minutes\n0 0 * * 0    Weekly on Sunday at midnight', difficulty: 'intermediate', examples: ['crontab -l', 'crontab -e', 'crontab -u user -l'] },
      { cmd: 'strace', desc: 'Trace system calls and signals for debugging', example: 'strace -p 1234 -e trace=file', syntax: 'strace [OPTIONS] COMMAND|PID', flags: '✦ ATTACHING:\n-p PID  Attach to a currently running process\n-f      Follow child processes as they are created\n\n✦ FILTERING & OUTPUT:\n-e trace=TYPE  Trace specific call types (e.g., file, network, process)\n-o FILE        Write trace output to a file instead of stderr\n-c             Count time, calls, and errors, and report a summary on exit', difficulty: 'advanced', examples: ['strace ls', 'strace -p 5678', 'strace -e trace=network curl URL'] },
    ]
  },
  {
    id: 'archive', label: '🗜️ Archives', color: '#0576b4', bg: 'rgba(5,118,180,0.1)', icon: '🗜️',
    commands: [
      { cmd: 'tar', desc: 'Tape archive — pack files into archive with optional compression', example: 'tar -czvf backup.tar.gz /var/www/', syntax: 'tar [OPTIONS] ARCHIVE [FILES]', flags: '✦ OPERATIONS:\n-c  Create a new archive\n-x  Extract files from an archive\n-t  List the contents of an archive\n\n✦ COMPRESSION:\n-z  Filter through gzip (.tar.gz or .tgz)\n-j  Filter through bzip2 (.tar.bz2)\n-J  Filter through xz (.tar.xz)\n\n✦ OTHER:\n-v  Verbose (list files processed)\n-f  Specify the archive filename\n-C  Change to a specific directory before extracting', difficulty: 'beginner', examples: ['tar -czvf arch.tar.gz dir/', 'tar -xvf archive.tar', 'tar -cJvf out.tar.xz files/'] },
      { cmd: 'zip / unzip', desc: 'Create and extract ZIP archives', example: 'zip -r site.zip ./public/', syntax: 'zip [OPTIONS] ARCHIVE FILES | unzip ARCHIVE', flags: '✦ ZIP OPTIONS:\n-r  Travel the directory structure recursively\n-9  Compress better (but slower)\n-e  Encrypt contents and prompt for a password\n-d  Delete files from a zip archive\n\n✦ UNZIP OPTIONS:\n-l  List archive files without extracting\n-d  Extract files into a specific directory', difficulty: 'beginner', examples: ['zip -r project.zip ./', 'unzip archive.zip', 'unzip -d /dest archive.zip'] },
      { cmd: 'gzip / gunzip', desc: 'Compress and decompress files using gzip format', example: 'gzip -k -9 large.log', syntax: 'gzip [OPTIONS] FILE', flags: '✦ COMPRESSION:\n-9  Best (maximum) compression (slowest)\n-1  Fastest compression (worst ratio)\n-k  Keep (do not delete) the original input files\n\n✦ DECOMPRESSION & INFO:\n-d  Decompress the file (equivalent to gunzip)\n-l  List compression ratio and sizes for each file\n-r  Travel the directory structure recursively', difficulty: 'beginner', examples: ['gzip file.txt', 'gunzip file.txt.gz', 'gzip -k -9 backup.sql'] },
      { cmd: 'xz', desc: 'High-ratio data compression utility (better than gzip)', example: 'xz -k -T4 large.bin', syntax: 'xz [OPTIONS] FILE', flags: '✦ COMPRESSION:\n-9  Extreme compression (uses more RAM and time)\n-z  Compress (default behavior)\n-T N  Use N threads for multi-threaded compression\n\n✦ DECOMPRESSION & INFO:\n-d  Decompress the file\n-k  Keep the original file (don\'t delete it)', difficulty: 'intermediate', examples: ['xz -k file.tar', 'xz -d file.tar.xz', 'xz -9 -T4 big.bin'] },
    ]
  },
  {
    id: 'git', label: '🔀 Git', color: '#bf3989', bg: 'rgba(191,57,137,0.1)', icon: '🔀',
    commands: [
      { cmd: 'git clone', desc: 'Clone a repository into a new directory', example: 'git clone --depth=1 https://github.com/user/repo.git', syntax: 'git clone [OPTIONS] URL [DIR]', flags: '✦ OPTIONS:\n--depth N  Create a shallow clone with a history truncated to N commits\n--branch   Clone only a specific branch or tag\n--bare     Create a bare repository (no working directory)\n--recurse-submodules  Initialize and clone submodules automatically', difficulty: 'beginner', examples: ['git clone https://github.com/repo.git', 'git clone --depth=1 --branch main URL'] },
      { cmd: 'git log', desc: 'Show commit history with rich formatting options', example: 'git log --oneline --graph --all', syntax: 'git log [OPTIONS] [RANGE]', flags: '✦ FORMATTING:\n--oneline  Show a compact format (hash + title)\n--graph    Draw a text-based graphical representation of branch history\n--stat     Show the number of inserted/deleted lines per file\n-p         Show the actual diff patch introduced by each commit\n\n✦ FILTERING:\n--all      Show commits from all branches\n--author   Filter commits by a specific author name\n--since    Show commits more recent than a specific date', difficulty: 'beginner', examples: ['git log --oneline -10', 'git log --graph --all', "git log --author='Name' --since='1 week'"] },
      { cmd: 'git stash', desc: 'Temporarily shelve changes and restore clean working state', example: 'git stash push -m "WIP feature"', syntax: 'git stash [COMMAND]', flags: '✦ COMMANDS:\npush -m  Save your local modifications to a new stash with a message\npop      Apply the most recent stash and remove it from the stash list\napply    Apply a stash but keep it in the stash list\nlist     Display all stashed modifications\ndrop     Delete a specific stash\nclear    Remove all stashed states entirely', difficulty: 'intermediate', examples: ['git stash', 'git stash push -m "feat"', 'git stash pop'] },
      { cmd: 'git rebase', desc: 'Reapply commits on top of another base commit', example: 'git rebase -i HEAD~5', syntax: 'git rebase [OPTIONS] [BASE]', flags: '✦ BEHAVIOR:\n-i      Interactive mode (allows squashing, rewording, dropping commits)\n--onto  Transplant a branch from one history onto another\n\n✦ CONFLICT RESOLUTION:\n--abort     Cancel the rebase operation entirely\n--continue  Resume the rebase after resolving a conflict\n--skip      Bypass the currently conflicting patch', difficulty: 'advanced', examples: ['git rebase main', 'git rebase -i HEAD~3', 'git rebase --onto newbase oldbase'] },
      { cmd: 'git bisect', desc: 'Binary search through commits to find a bug', example: 'git bisect start; git bisect bad; git bisect good v1.0', syntax: 'git bisect [start|good|bad|reset]', flags: '✦ PROCESS:\nstart    Start a bisect session\nbad      Mark the current or specified commit as bad (broken)\ngood     Mark a specified commit as good (working)\nreset    Clean up the bisect state and return to the original branch\nrun CMD  Automate the bisect process by running a script at each step', difficulty: 'advanced', examples: ['git bisect start', 'git bisect bad HEAD', 'git bisect good v2.0'] },
      { cmd: 'git cherry-pick', desc: 'Apply the changes from specific commits to current branch', example: 'git cherry-pick abc1234', syntax: 'git cherry-pick [OPTIONS] COMMIT', flags: '✦ OPTIONS:\n-n  Apply the changes to your working tree without making a commit\n-e  Edit the commit message before committing\n-x  Append a line indicating the original commit hash\n--abort  Cancel the operation if it results in conflicts', difficulty: 'intermediate', examples: ['git cherry-pick a1b2c3', 'git cherry-pick -n HEAD~2', 'git cherry-pick first^..last'] },
    ]
  },
  {
    id: 'scripting', label: '📜 Scripting', color: '#1a7f37', bg: 'rgba(26,127,55,0.1)', icon: '📜',
    commands: [
      { cmd: 'bash', desc: 'Execute shell scripts and start interactive bash sessions', example: 'bash -x deploy.sh', syntax: 'bash [OPTIONS] [SCRIPT]', flags: '✦ EXECUTION & DEBUGGING:\n-x  Print commands and their arguments as they are executed\n-e  Exit immediately if a pipeline or command returns a non-zero status\n-u  Treat unset variables as an error when substituting\n-o pipefail  Return value of a pipeline is the status of the last failing command\n-n  Read commands but do not execute them (syntax checking)\n-c  Read and execute commands from a string', difficulty: 'beginner', examples: ['bash script.sh', 'bash -x debug.sh', 'bash -n check_syntax.sh'] },
      { cmd: 'env / export', desc: 'Manage environment variables in shell sessions', example: 'export DATABASE_URL="postgres://..."', syntax: 'env | export VAR=VALUE', flags: '✦ USAGE:\nenv         Print all currently exported environment variables\nenv -i      Execute a command in an empty environment\nexport VAR  Mark a variable to be passed to child processes\nunset VAR   Remove a variable or function completely\nprintenv    Print the value of a specific environment variable', difficulty: 'beginner', examples: ['env | grep PATH', 'export NODE_ENV=production', 'printenv HOME'] },
      { cmd: 'source / .', desc: 'Execute commands from a file in current shell', example: 'source ~/.bashrc', syntax: 'source FILE | . FILE', flags: '✦ CONCEPTS:\n* `source` executes commands in the CURRENT shell environment (does not spawn a subshell).\n* `.` is the POSIX standard equivalent of `source`.\n* Commonly used to load `.env` files, functions, aliases, or activate virtual environments.', difficulty: 'beginner', examples: ['source ~/.bashrc', 'source venv/bin/activate', '. .env'] },
      { cmd: 'tee', desc: 'Read from stdin and write to both stdout and files', example: 'command | tee -a output.log', syntax: 'tee [OPTIONS] [FILE...]', flags: '✦ OPTIONS:\n-a  Append to the given files, do not overwrite them\n-i  Ignore interrupt signals\n\n✦ USAGE NOTE:\n* Frequently used in command pipelines to allow viewing output on the screen while simultaneously saving it to a log file.', difficulty: 'intermediate', examples: ['ls | tee files.txt', 'make 2>&1 | tee build.log', 'cmd | tee -a daily.log'] },
      { cmd: 'trap', desc: 'Execute commands when shell receives signals or exits', example: 'trap "rm -f /tmp/lock" EXIT', syntax: 'trap [COMMAND] [SIGNAL...]', flags: '✦ COMMON SIGNALS:\nEXIT     Executed when the shell script exits (normally or via error)\nSIGINT   Triggered when the user presses Ctrl+C\nSIGTERM  Triggered when a termination signal is sent\nERR      Executed when any command fails (non-zero exit)\nDEBUG    Executed before every single command', difficulty: 'advanced', examples: ['trap cleanup EXIT', 'trap "echo Interrupted" INT', 'trap "log_error $?" ERR'] },
      { cmd: 'printf', desc: 'Format and print data — more powerful than echo', example: 'printf "%-20s %5s\\n" Name Age', syntax: 'printf FORMAT [ARGS]', flags: '✦ FORMAT SPECIFIERS:\n%s  A string of characters\n%d  An integer number\n%f  A floating-point number\n%x  A hexadecimal number\n%-N Left-align the field to width N (e.g., %-10s)\n\\n  Insert a newline character\n\\t  Insert a tab character', difficulty: 'intermediate', examples: ['printf "Hello %s\\n" World', 'printf "%d\\n" 0xFF', 'printf "%-15s %d\\n" Name 42'] },
      { cmd: 'read', desc: 'Read a line from stdin into shell variables', example: 'read -p "Enter name: " -t 30 name', syntax: 'read [OPTIONS] [VAR...]', flags: '✦ OPTIONS:\n-p  Output a prompt string without a trailing newline\n-t  Set a timeout in seconds (returns error if exceeded)\n-s  Silent mode (characters are not echoed, useful for passwords)\n-r  Raw mode (do not treat backslashes as escape characters)\n-a  Read the input words into an array variable', difficulty: 'intermediate', examples: ['read name', 'read -sp "Password: " pwd', 'read -t 10 -p "Continue? " ans'] },
    ]
  }
];

let html = fs.readFileSync('linux-commands.html', 'utf8');

// Stringify the categories and embed them safely
const newCategoriesStr = 'const CATEGORIES = ' + JSON.stringify(categories, null, 2) + ';';
html = html.replace(/const CATEGORIES = \[\s*[\s\S]*?\];\n/m, newCategoriesStr + '\n');

fs.writeFileSync('linux-commands.html', html);
console.log('Successfully updated linux-commands.html');
